version: '3.8'

services:
  # Serviço para o MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_database
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: queimas_banco
      MYSQL_USER: senac
      MYSQL_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./backend/src/main/resources/scripts:/docker-entrypoint-initdb.d
    networks:
      - network-queimas
# Serviço para a sua aplicação Java
  java_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - network-queimas
# Serviço para o frontend
  frontend:
    build:
       context: ./frontend
       dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
       - "5200:4200"
    depends_on:
      - java_app
    networks:
      - network-queimas
# Criando network
networks:
  network-queimas:
     